services:
  app:
    container_name: symfony-deployment-example
    image: fredericbui/symfony_deployment
    ports:
      - "8089:80"
  db:
    image: mysql:8.0
    container_name: symfony_db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: